'less' updates
Removed userconfig/standard_dotfiles/.init/contrib/less_458

Added userconfig/standard_dotfiles/.init/contrib/less_487
(from Debian "buster") 

Added userconfig/standard_dotfiles/.lessfilter, used by lesspipe
(currently supports *.lz4, *.docx and *.ods; the latter two via odt2txt or unoconv)


git-svn-id: svn+ssh://al.id.au/srv/svn/tools/userconfig/standard_dotfiles@384 6f3dbf8f-7d3b-0410-9ec1-89cb43d465ab

diff --git a/.init/contrib/less_487/lesspipe b/.init/contrib/less_487/lesspipe
--- a/.init/contrib/less_487/lesspipe
+++ b/.init/contrib/less_487/lesspipe
@@ -50,10 +50,7 @@ if [ $# -eq 1 ] ; then
 	if [ $BASENAME = $LESSFILE ]; then
 		TMPFILE=`tempfile -d $TMPDIR -p lessf`
 		if [ -z "$TMPFILE" ]; then
-			TMPFILE=`mktemp -t lessfXXXXXX`
-		fi
-		if [ -z "$TMPFILE" ]; then
-			echo >&2 "Could not find essential program 'tempfile' or fallback 'mktemp'. Exiting"
+			echo >&2 "Could not find essential program 'tempfile'. Exiting"
       exit 1
 		fi
 	fi
@@ -101,7 +98,7 @@ if [ $# -eq 1 ] ; then
 				if [ -x "`which bunzip2`" ]; then bunzip2 -dc "$1"
 				else echo "No bunzip2 available"; fi ;;
 
-			*.deb|*.udeb|*.ddeb)
+			*.deb|*.udeb|*.ddeb|*.ipk)
 				echo "$1:"; dpkg --info "$1"
 				echo
 				echo '*** Contents:'; dpkg-deb --contents "$1"
@@ -117,6 +114,17 @@ if [ $# -eq 1 ] ; then
 					else
 						echo "No catdoc available";
 					fi
+				fi
+				;;
+
+			*.egg)
+				if [ -x "`which unzip`" ]; then
+					unzip -p "$1" EGG-INFO/PKG-INFO | \
+						sed '/^Description:/,/^\S/{/^Description:/d; /^\S/b; d}'
+					echo
+					unzip -v "$1"
+				else
+					echo "No unzip available"
 				fi
 				;;
 
@@ -195,6 +203,13 @@ if [ $# -eq 1 ] ; then
 					rpm -q -l -p "$1"
 				else echo "rpm isn't available, no query on rpm package possible"; fi ;;
 
+                        *.snap)
+                            if [ -x "`which snap`" ]; then snap info "$1"; fi
+                            if [ -x "`which unsquashfs`" ]; then
+                                echo
+                                echo '*** Contents:'; unsquashfs -ll -d '' "$1" 
+                            else echo "No unsquashfs available"; fi ;;
+                        
 			*.tar.gz|*.tgz|*.tar.z|*.tar.dz)
 				tar tzvf "$1" --force-local
 				;;
@@ -204,6 +219,15 @@ if [ $# -eq 1 ] ; then
 					xz -dc "$1" | tar tfvv -
 				else
 					echo "No xz available"
+				fi
+				;;
+
+			*.whl)
+				if [ -x "`which unzip`" ]; then
+					unzip -p "$1" '*.dist-info/METADATA' | sed '/^$/q'
+					unzip -v "$1"
+				else
+		 			echo "No unzip available"
 				fi
 				;;
 
