userconfig/standard_dotfiles/.init/contrib/less_458/lesspipe:   falls back to mktemp if tempfile doesn't exist or doesn't work
git-svn-id: svn+ssh://al.id.au/srv/svn/tools/userconfig/standard_dotfiles@201 6f3dbf8f-7d3b-0410-9ec1-89cb43d465ab

diff --git a/.init/contrib/less_458/lesspipe b/.init/contrib/less_458/lesspipe
--- a/.init/contrib/less_458/lesspipe
+++ b/.init/contrib/less_458/lesspipe
@@ -50,7 +50,10 @@ if [ $# -eq 1 ] ; then
 	if [ $BASENAME = $LESSFILE ]; then
 		TMPFILE=`tempfile -d $TMPDIR -p lessf`
 		if [ -z "$TMPFILE" ]; then
-			echo >&2 "Could not find essential program 'tempfile'. Exiting"
+			TMPFILE=`mktemp -t lessfXXXXXX`
+		fi
+		if [ -z "$TMPFILE" ]; then
+			echo >&2 "Could not find essential program 'tempfile' or fallback 'mktemp'. Exiting"
       exit 1
 		fi
 	fi
